#!/usr/bin/env bash
# Boot xv6 in QEMU with GDB stub, then connect GDB in the same terminal.
# Run this from the project root. In VS Code, use the "xv6: debug" task instead,
# which opens QEMU in one panel and leaves your terminal free for GDB.
set -euo pipefail

KERNEL_DIR="$(dirname "$0")/../kernel/xv6-riscv"
cd "$KERNEL_DIR"

# Start QEMU in the background with GDB stub
make qemu-gdb &
QEMU_PID=$!

# Wait for the GDB port to open
sleep 1

# Connect GDB (uses .gdbinit generated by make)
riscv64-unknown-elf-gdb kernel/kernel

# Kill QEMU when GDB exits
kill "$QEMU_PID" 2>/dev/null || true
